# coding: utf-8

"""
    Administrative API Documentation

    The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.token_processor_to_token_generator_mappings_api import TokenProcessorToTokenGeneratorMappingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTokenProcessorToTokenGeneratorMappingsApi(unittest.TestCase):
    """TokenProcessorToTokenGeneratorMappingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.token_processor_to_token_generator_mappings_api.TokenProcessorToTokenGeneratorMappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_token_to_token_mapping(self):
        """Test case for create_token_to_token_mapping

        Create a new Token Processor to Token Generator Mapping.  # noqa: E501
        """
        pass

    def test_delete_token_to_token_mapping_by_id(self):
        """Test case for delete_token_to_token_mapping_by_id

        Delete a Token Processor to Token Generator Mapping.  # noqa: E501
        """
        pass

    def test_get_token_to_token_mapping_by_id(self):
        """Test case for get_token_to_token_mapping_by_id

        Get a Token Processor to Token Generator Mapping.  # noqa: E501
        """
        pass

    def test_get_token_to_token_mappings(self):
        """Test case for get_token_to_token_mappings

        Get the list of Token Processor to Token Generator Mappings.  # noqa: E501
        """
        pass

    def test_update_token_to_token_mapping_by_id(self):
        """Test case for update_token_to_token_mapping_by_id

        Update a Token Processor to Token Generator Mapping.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
