# coding: utf-8

"""
    Administrative API Documentation

    The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.idptoken_processors_api import IdptokenProcessorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIdptokenProcessorsApi(unittest.TestCase):
    """IdptokenProcessorsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.idptoken_processors_api.IdptokenProcessorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_token_processor(self):
        """Test case for create_token_processor

        Create a new token processor instance.  # noqa: E501
        """
        pass

    def test_delete_token_processor(self):
        """Test case for delete_token_processor

        Delete a token processor instance.  # noqa: E501
        """
        pass

    def test_get_token_processor(self):
        """Test case for get_token_processor

        Find a token processor instance by ID.  # noqa: E501
        """
        pass

    def test_get_token_processor_descriptors(self):
        """Test case for get_token_processor_descriptors

        Get the list of available token processors.  # noqa: E501
        """
        pass

    def test_get_token_processor_descriptors_by_id(self):
        """Test case for get_token_processor_descriptors_by_id

        Get the description of a token processor plugin by ID.  # noqa: E501
        """
        pass

    def test_get_token_processors(self):
        """Test case for get_token_processors

        Get the list of token processor instances.  # noqa: E501
        """
        pass

    def test_update_token_processor(self):
        """Test case for update_token_processor

        Update a token processor instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
