# coding: utf-8

"""
    Administrative API Documentation

    The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.idp_to_sp_adapter_mapping_api import IdpToSpAdapterMappingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIdpToSpAdapterMappingApi(unittest.TestCase):
    """IdpToSpAdapterMappingApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.idp_to_sp_adapter_mapping_api.IdpToSpAdapterMappingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_idp_to_sp_adapter_mapping(self):
        """Test case for create_idp_to_sp_adapter_mapping

        Create a new IdP-to-SP Adapter mapping.  # noqa: E501
        """
        pass

    def test_delete_idp_to_sp_adapter_mappings_by_id(self):
        """Test case for delete_idp_to_sp_adapter_mappings_by_id

        Delete an Adapter to Adapter Mapping.  # noqa: E501
        """
        pass

    def test_get_idp_to_sp_adapter_mappings(self):
        """Test case for get_idp_to_sp_adapter_mappings

        Get list of IdP-to-SP Adapter Mappings.  # noqa: E501
        """
        pass

    def test_get_idp_to_sp_adapter_mappings_by_id(self):
        """Test case for get_idp_to_sp_adapter_mappings_by_id

        Get an IdP-to-SP Adapter Mapping.  # noqa: E501
        """
        pass

    def test_update_idp_to_sp_adapter_mapping(self):
        """Test case for update_idp_to_sp_adapter_mapping

        Update the specified IdP-to-SP Adapter mapping.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
