# coding: utf-8

"""
    Administrative API Documentation

    The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.oauthauthentication_policy_contract_mappings_api import OauthauthenticationPolicyContractMappingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOauthauthenticationPolicyContractMappingsApi(unittest.TestCase):
    """OauthauthenticationPolicyContractMappingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.oauthauthentication_policy_contract_mappings_api.OauthauthenticationPolicyContractMappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_apc_mapping(self):
        """Test case for create_apc_mapping

        Create a new authentication policy contract to persistent grant mapping.  # noqa: E501
        """
        pass

    def test_delete_apc_mapping(self):
        """Test case for delete_apc_mapping

        Delete an authentication policy contract to persistent grant mapping.  # noqa: E501
        """
        pass

    def test_get_apc_mapping(self):
        """Test case for get_apc_mapping

        Find the authentication policy contract to persistent grant mapping by ID.  # noqa: E501
        """
        pass

    def test_get_apc_mappings(self):
        """Test case for get_apc_mappings

        Get the list of authentication policy contract to persistent grant mappings.  # noqa: E501
        """
        pass

    def test_update_apc_mapping(self):
        """Test case for update_apc_mapping

        Update an authentication policy contract to persistent grant mapping.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
