# coding: utf-8

"""
    Administrative API Documentation

    The PingFederate Administrative API is a REST-based interface that provides a programmatic way to make configuration changes to PingFederate as an alternative to using the administrative console.<br/><br/>Expand the resources below to display implementation details on that resource such as the available endpoints, the parameter and response models for the operation, and the model structure of the resources themselves. Each resource operation comes with the ability to interact with the API. You are prompted for proper administration credentials when you try to perform an API operation.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ProfileConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delete_identity_enabled': 'bool',
        'template_name': 'str'
    }

    attribute_map = {
        'delete_identity_enabled': 'deleteIdentityEnabled',
        'template_name': 'templateName'
    }

    def __init__(self, delete_identity_enabled=None, template_name=None, _configuration=None):  # noqa: E501
        """ProfileConfig - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._delete_identity_enabled = None
        self._template_name = None
        self.discriminator = None

        if delete_identity_enabled is not None:
            self.delete_identity_enabled = delete_identity_enabled
        self.template_name = template_name

    @property
    def delete_identity_enabled(self):
        """Gets the delete_identity_enabled of this ProfileConfig.  # noqa: E501

        Whether the end user is allowed to use delete functionality.  # noqa: E501

        :return: The delete_identity_enabled of this ProfileConfig.  # noqa: E501
        :rtype: bool
        """
        return self._delete_identity_enabled

    @delete_identity_enabled.setter
    def delete_identity_enabled(self, delete_identity_enabled):
        """Sets the delete_identity_enabled of this ProfileConfig.

        Whether the end user is allowed to use delete functionality.  # noqa: E501

        :param delete_identity_enabled: The delete_identity_enabled of this ProfileConfig.  # noqa: E501
        :type: bool
        """

        self._delete_identity_enabled = delete_identity_enabled

    @property
    def template_name(self):
        """Gets the template_name of this ProfileConfig.  # noqa: E501

        The template name for end-user profile management.  # noqa: E501

        :return: The template_name of this ProfileConfig.  # noqa: E501
        :rtype: str
        """
        return self._template_name

    @template_name.setter
    def template_name(self, template_name):
        """Sets the template_name of this ProfileConfig.

        The template name for end-user profile management.  # noqa: E501

        :param template_name: The template_name of this ProfileConfig.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and template_name is None:
            raise ValueError("Invalid value for `template_name`, must not be `None`")  # noqa: E501

        self._template_name = template_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProfileConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProfileConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProfileConfig):
            return True

        return self.to_dict() != other.to_dict()
